env: 
  global: 
    - CASADIVERSION=3.1.0


dist: trusty

before_script:
  - set -e

script:
  - popd
  - cd examples
  - |
    cat <<EOF  > matplotlibrc
    backend : Template
    EOF
  - python sysid.py && python multipleshooting.py && python misc.py && python inverse.py && python rosenbrock.py && python fit.py && python codegen.py
  
branches:
  except:
    - /.*appveyor.*/

before_install:
  - export MATPLOTLIBRC=`pwd`
  - |
    cat <<EOF >matplotlibrc
    backend : Template
    EOF
  - sudo apt-get update -qq
  - sudo apt-get install -y python-numpy python-scipy python-matplotlib libgomp1
  - pushd ../../
  - wget http://sourceforge.net/projects/casadi/files/CasADi/$CASADIVERSION/linux/casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz/download -O casadi.tar.gz
  - mkdir casadi-build && tar -xf casadi.tar.gz -C casadi-build
  - ls casadi-build
  - pwd
  - export PYTHONPATH=/home/travis/build/casadi-build/:/home/travis/build/casadi/python-optistack/
language: cpp
